---
title: "Impact de la COVID-19 sur les déplacements de personnes en Wallonie"
author: "Alex Godin, Jeff Loiseau, Valentin Picart, Valentin Vandenbosche"
format:
  pdf:
    documentclass: report
    toc: true
editor: visual
lang: fr
bibliography: references.bib
---

<!--# Ce travail doit faire entre 15 et 20 pages.-->

<!--# Un rapport est différent d'un carnet de notes. Il ne s'agit donc pas de faire du copier-coller d'un document vers l'autre. Un rapport de synthèse doit être compréhensible sans devoir lire le carnet de notes. Le rapport de synthèse doit être  rédigé avec un style et une présentation adéquats. -->

## Introduction

<!--% Rédigez l'introduction de ce rapport.-->

La pandémie de COVID‑19, causée par le SARS‑CoV‑2 apparu fin 2019 en Chine, a été déclarée pandémie mondiale par l’OMS le 11 mars 2020 [@universalis2020]. Elle a entraîné plusieurs vagues successives, marquées par l’émergence de variants et des mesures de confinement à l’échelle planétaire [@wikipediaChronologie2020].

En Europe, la propagation rapide du virus a conduit à des restrictions majeures dès le printemps 2020, avec fermetures de frontières, confinement et campagnes de vaccination massives [@touteleurope2020].

En Belgique, le premier cas a été confirmé le 4 février 2020 à Bruxelles [@wikipediaBelgique2020]. Le pays a connu plusieurs vagues sévères, notamment en mars et novembre 2020, entraînant des confinements stricts et une forte pression sur les hôpitaux. Selon Sciensano, plus de 4,6 millions de cas et près de 33 500 décès ont été enregistrés début 2023 [@wikipediaBelgique2020].

La campagne de vaccination, lancée fin 2020, a permis de réduire la gravité des infections et de stabiliser la situation sanitaire en 2022. La phase fédérale de gestion de crise a pris fin en mars 2022, marquant le passage à une surveillance épidémiologique régulière [@centredecrise2022].

## But

<!--% Rédigez le but de ce rapport.-->

VALOU

## Matériel et méthodes

<!--% Cette section doit comprendre deux parties. La première partie doit expliciter le données employées et la seconde traiter des analyses réalisées et des logiciels employés.-->

Nous avons utilisé les *Community Mobility Reports* de Google, basés sur des données anonymisées de Google Maps, afin d’analyser les variations de mobilité liées aux mesures COVID-19.

Les rapports n’étant plus mis à jour depuis octobre 2022, nous avons exploité les données historiques pour la Wallonie sur les années 2020, 2021 et 2022, avec un focus particulier sur 2020 et 2021. Une application interactive est disponible à l'adresse suivante <https://dimiter.shinyapps.io/covid-19_mobility/> , permet de visualiser de manière dynamique les données.

Ces données sont exprimées en variation de pourcentage par rapport à une période de référence pré-pandémique, correspondant à la médiane des déplacements observés entre le 3 janvier et le 6 février 2020. Elles sont structurées en six grandes catégories : commerces et loisirs ("com_loi"), épiceries et pharmacies ("alim_pharma"), parcs ("parcs"), transports en commun ("tec"), lieux de travail ("travail")et lieux de résidence ("residence").

L'analyse est réalisée avec la SciViews Box 2025 dans Saturn Cloud (Linux Ubuntu 22.04), utilisant le logiciel R (r R.version.string). Le package {pastecs} version r packageVersion("pastecs") est utilisé pour étudier la série temporelle.

## Résultats

<!--% Présentez les analyses les plus pertinents que vous avez sélectionnés. Structurez la section en partie avec des titres explicites de niveau trois.-->

## Discussion et Conclusion

<!--% En tenant compte du but de votre carnet de notes et de vos résultats, discutez de résultats et proposez des conclusions à votre analyse en 5 à 10 phrases. -->
